"""add metric_samples table

Revision ID: 87683b947d4f
Revises: 3aa90f0ee0b1
Create Date: 2026-06-30 16:43:08.155601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87683b947d4f'
down_revision: Union[str, Sequence[str], None] = '3aa90f0ee0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_samples_metric_name'), 'metric_samples', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metric_samples_recorded_at'), 'metric_samples', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_metric_samples_target_id'), 'metric_samples', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_samples_target_id'), table_name='metric_samples')
    op.drop_index(op.f('ix_metric_samples_recorded_at'), table_name='metric_samples')
    op.drop_index(op.f('ix_metric_samples_metric_name'), table_name='metric_samples')
    op.drop_table('metric_samples')
    # ### end Alembic commands ###
